# Generated by Django 2.0.7 on 2018-07-31 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuites', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tuite',
            options={'ordering': ('-content',)},
        ),
        migrations.AlterField(
            model_name='tuite',
            name='content',
            field=models.CharField(max_length=280, verbose_name='Tuite'),
        ),
    ]
